platform :ios, '9.0'

target 'Darts301' do
  use_frameworks!
  # Pods for Darts301
  pod 'Firebase/AdMob'
  pod 'Firebase/Core'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
  pod 'UIImage+animatedGif', '~> 0.1'
end
