platform :ios, '10.0'

target 'Darts301' do
  use_frameworks!
  # Pods for Darts301
  pod 'Firebase/AdMob'
  pod 'Firebase/Core'
  pod 'SwiftValidator', :git => 'https://github.com/SwiftValidatorCommunity/SwiftValidator.git', :tag => '5.0.0'
  pod 'UIImage+animatedGif', '~> 0.1'
end
